//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataDll
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsFound
    {
        public int foundId { get; set; }
        public int searchId { get; set; }
        public string fileName { get; set; }
    }
}
